require('p5');

module.exports = {
    x: 300,
    y: 300,
    y2: 600,
    // velY: 3,
    // vel2Y: 3,
    // velX: 3,
    velYsign: 1,
    velY2sign: 1,
    velXsign: 1,
    balls: [],
    totalWaterFrames: 879,
    waterFrames: [],
    currentFrame: 0,
    // waterVel: 3,
    waterVelSign: 1,
    pings: [],
    pingVelocityConst: 60,
    pingVelocity: 60,
    currentBall: 1,
    isPlaying: 1,
    sound: null,
    tracks: null,
    currentTrack: null,
    amplitude: null,
    amplitudeBandPass: null,
    level: null,
    levelBandPass: null,
    levelVel: null,
    size: null,
    fft: null,
    bandPass: null,
    gain1: null,
    gain2: null,
    gainMaster: null,
    aspectRatio: null,
    ballSize: null,
    glch: null,
    amorph: null,
    vid: null,
    pingRadius: null,
    ballLevel: null,
    ballSizeLevel: null,
    isMobile: false,
    mobileTouched: false,
    totalLoadItems: null,
    loadedItems: 0
};
